name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [created]

jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y g++ make dpkg-dev

      - name: Make scripts executable
        run: chmod +x cicd/*.sh

      - name: Run build
        run: ./cicd/build.sh

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: lab2-binary
          path: src/lab2

  test:
    name: 🧪 Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x cicd/*.sh

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: lab2-binary
          path: src/

      - name: Make binary executable
        run: chmod +x src/lab2

      - name: Run tests
        run: ./cicd/test.sh

  package:
    name: 📦 Package
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x cicd/*.sh

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: lab2-binary
          path: src/

      - name: Make binary executable
        run: chmod +x src/lab2

      - name: Install packaging tools
        run: sudo apt-get install -y dpkg-dev

      - name: Build deb package
        run: ./cicd/package.sh

      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: lab2-var11-1.0.0.deb

  docker:
    name: 🐳 Docker Build (локально)
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download deb package
        uses: actions/download-artifact@v4
        with:
          name: deb-package
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image locally
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # образ останется локально
          tags: lab2-local:latest

      - name: Check Docker image
        run: docker images | grep lab2-local

  release:
    name: 🚀 Release
    needs: package
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Релиз job сработала! Можно делать любые действия здесь."
      - run: ls -lh lab2-var11-1.0.0.deb
