name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make dpkg-dev

      - name: Give execute permission
        run: chmod +x cicd/build.sh cicd/test.sh cicd/package.sh

      - name: Build
        run: ./cicd/build.sh

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: lab2-binary
          path: src/lab2

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Give execute permission
        run: chmod +x cicd/build.sh cicd/test.sh cicd/package.sh

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: lab2-binary
          path: src/

      - name: Make executable
        run: chmod +x src/lab2

      - name: Run tests
        run: ./cicd/test.sh

  package:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Give execute permission
        run: chmod +x cicd/build.sh cicd/test.sh cicd/package.sh

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: lab2-binary
          path: src/

      - name: Make executable
        run: chmod +x src/lab2

      - name: Install packaging tools
        run: sudo apt-get install -y dpkg-dev

      - name: Build deb package
        run: ./cicd/package.sh

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: lab2-var11-1.0.0.deb
